# Hugo Configuration
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LIFE AND MATHEMATICAL SCIENCES'
theme = 'blowfish'

# Enable GitInfo for last modified date
enableGitInfo = true

# Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Needed for Blowfish
paginate = 10
