# Hugo Configuration
baseURL = 'https://www.inoue-lab.info/'
languageCode = 'en-us'
title = '生命数理科学分野'
# theme = 'blowfish' # Removed for Hugo Modules

# Enable GitInfo for last modified date
enableGitInfo = false

# Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Needed for Blowfish
paginate = 10

[languages]
  [languages."en-us"]
    languageName = "English"
    weight = 1
    [languages."en-us".params]
      dateFormat = "January 2, 2006"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # この行を確認・追加 (trueにする)