# Hugo Configuration

baseURL = 'https://www.inoue-lab.info/'
defaultContentLanguage = "ja" #
defaultContentLanguageInsubdir = true
outputs.home = ["HTML", "RSS", "JSON"]

# Enable GitInfo for last modified date
enableGitInfo = false

# Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Needed for Blowfish
paginate = 10


      
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true # この行を確認・追加 (trueにする)

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

