# Hugo Configuration
baseURL = 'https://www.inoue-lab.info/'
languageCode = 'ja'
defaultContentLanguage = "ja" # Explicitly set default language
title = '生命数理科学分野'
# theme = 'blowfish' # Removed for Hugo Modules

# Enable GitInfo for last modified date
enableGitInfo = false

# Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Needed for Blowfish
paginate = 10

[languages]
  [languages."ja"]
    languageName = "日本語" # Changed to Japanese
    weight = 1
    [languages."ja".params]
      dateFormat = "2006年1月2日" # Changed to Japanese date format

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # この行を確認・追加 (trueにする)

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
