# config/_default/languages.ja.toml

title = "生命数理科学分野" # Matched with hugo.toml title

[params.author]
name = "生命数理科学分野"
image = "image/flowers.jpg"
#headline = "一般的に素晴らしい人間" # Commented out placeholder
#bio = "私について少し" # Commented out placeholder
links = [
  { github = "https://github.com/yasuhiroinoue" },
  { researchmap = "https://researchmap.jp/yasuhiroinoue" },
  { youtube = "https://www.youtube.com/@yasuhiroinoue" }
]
