# config/_default/languages.en.toml

title = "Life and Mathematical Sciences" # Matched with hugo.toml title

[params.author]
name = "Life and Mathematical Sciences"
image = "image/flowers.jpg"
links = [
  { github = "https://github.com/yasuhiroinoue" },
  { orcid = "https://orcid.org/my-orcid?orcid=0000-0002-1968-8883" },
  { youtube = "https://www.youtube.com/@yasuhiroinoue" }
]
