[[main]]
  name = "ホーム" # Changed to Japanese
  url = "/"
  weight = 1
[[main]]
  name = "お知らせ"
  url = "/ja/news/"
  weight = 5
[[main]]
  name = "メンバー"
  url = "/ja/members/"
  weight = 10
[[main]]
  name = "研究室を希望される方へ"
  url = "/ja/prospective-students/"
  weight = 20
[[main]]
  name = "YouTube"
  url = "/ja/youtube/"
  weight = 15
