# Blowfish Theme Parameters
# Documentation: https://blowfish.page/docs/configuration/

# Meta description for the site
description = "京都大学 生命数理科学分野" # Changed to Japanese

# Default theme settings
# Options: "light", "dark", "auto"
colorScheme = "blowfish"
# Whether to show the scheme toggle in the header
showSchemeToggle = true

# Footer settings
footer.showCopyright = true
footer.showThemeAttribution = true
footer.showScrollToTop = true

# Homepage settings
homepage.layout = "card" # Default layout, can be changed later
homepage.showRecent = true  # Show recent content (like our news items)
homepage.homepageImage = "image/blackboard.jpg" # Changed to Japanese