baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LIFE AND MATHEMATICAL SCIENCES'
theme = 'ananke'

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "お知らせ"
  url = "/news/"
  weight = 5
[[menu.main]]
  name = "メンバー"
  url = "/members/"
  weight = 10
[[menu.main]]
  name = "研究室を希望される方へ"
  url = "/prospective-students/"
  weight = 20
